name: Deploy to Dev

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:

  deploy:
    name: deploy to vm
    runs-on: ubuntu-latest
    
    steps:

    - name: add ssh key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./id_rsa
        chmod 600 id_rsa


    - name: connect and pull
      run: ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'bash -i -c "cd ${{ secrets.WORK_DIR }} && git pull && npm i && pm2 restart 4 "'

    - name: cleanup
      run: rm -rf ~/.ssh